---
- name: To install wildfly app
  hosts: all
  become: yes
  tasks:
    - name: To install java
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: true
        state: present
    - name: To add group
      ansible.builtin.group:
        name: wildfly
        state: present
    - name: To add user
      ansible.builtin.user:
        name: wildfly
        shell: /sbin/nologin
        create_home: yes 
        home: /opt/wildfly
        group: wildfly
        state: present
    - name: To extract wildfly
      ansible.builtin.unarchive:
        src: https://download.jboss.org/wildfly/16.0.0.Final/wildfly-16.0.0.Final.tar.gz
        remote_src: yes
        dest: /opt/
    - name: To create symbolic link
      ansible.builtin.file:
        src: /opt/wildfly-16.0.0.Final
        dest: /opt/wildfly/latest
        state: link
    - name: To change the ownership
      ansible.builtin.file:
        dest: /opt/wildfly
        group: wildfly
        owner: wildfly
        recurse: true
    - name: To create directory
      ansible.builtin.file:
        path: /etc/wildfly
        owner: wildfly
        group: wildfly
        state: directory 
    - name: To copy conf file
      ansible.builtin.copy:
        src: /opt/wildfly/latest/docs/contrib/scripts/systemd/wildfly.conf 
        dest: /etc/wildfly/
        remote_src: true
    - name: To copy launch file
      ansible.builtin.copy:
        src: /opt/wildfly/latest/docs/contrib/scripts/systemd/launch.sh
        dest: /opt/wildfly/bin/
    - name: add execute permissions to shell files
      ansible.builtin.command: "sudo sh -c 'chmod +x /opt/wildfly/bin/*.sh'"
    - name: To copy systemd file
      ansible.builtin.copy:
        src: /opt/wildfly/latest/docs/contrib/scripts/systemd/wildfly.service
        dest: /etc/systemd/system/
    

      

    